# Generated by Django 5.2 on 2025-04-30 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_category_options_alter_subtask_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtask',
            options={'default_related_name': 'subtasks', 'ordering': ('create_date',), 'verbose_name': 'Позадача', 'verbose_name_plural': 'Подзадачи'},
        ),
    ]
