# Generated by Django 5.2 on 2025-05-03 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_subtask_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-create_date',), 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
